postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: gympoint

mongodb:
  image: mongo
  ports:
    - "27017:27017"

redis:
  image: redis:alpine
  ports:
    - "6379:6379"
